In [6]:
import numpy as np
import nrrd
import sys
import mahotas as mh

In [2]:
image = '10.img.nrrd'
label = '10.a.seg.nrrd'

In [3]:
img = nrrd.read(image)
labl = nrrd.read(label)

In [4]:
print(img)

(array([[[ -101,   -98,   -92, ..., -1004,  -997,  -996],
        [ -110,  -102,  -101, ..., -1005,  -998,  -995],
        [ -114,  -104,  -111, ..., -1003,  -998,  -995],
        ...,
        [  107,   108,   104, ..., -1006, -1004, -1005],
        [  118,   120,   128, ..., -1006, -1006, -1005],
        [  121,   122,   130, ..., -1006, -1005, -1003]],

       [[ -102,  -101,   -93, ..., -1004,  -997,  -994],
        [ -113,  -112,   -97, ..., -1003,  -999,  -994],
        [ -114,  -115,  -107, ..., -1001,  -999,  -994],
        ...,
        [   91,    98,    99, ..., -1005, -1004, -1004],
        [  105,   107,   125, ..., -1005, -1006, -1005],
        [  121,   121,   131, ..., -1005, -1006, -1004]],

       [[ -100,   -98,   -97, ..., -1002,  -998,  -994],
        [ -111,  -113,   -99, ..., -1000, -1000,  -994],
        [ -113,  -121,  -107, ...,  -997,  -999,  -993],
        ...,
        [   83,    84,    88, ..., -1005, -1003, -1001],
        [  102,    96,   112, ..., -1004, -1

In [31]:
img[1]

OrderedDict([('type', 'short'),
             ('dimension', 3),
             ('space', 'left-posterior-superior'),
             ('sizes', array([512, 512, 234])),
             ('space directions',
              array([[0.46875, 0.     , 0.     ],
                     [0.     , 0.46875, 0.     ],
                     [0.     , 0.     , 1.5    ]])),
             ('kinds', ['domain', 'domain', 'domain']),
             ('endian', 'little'),
             ('encoding', 'gzip'),
             ('space origin', array([-102.765625, -288.765625,  863.      ]))])

In [5]:
print(labl)

(array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ...,

In [30]:
labl[1]

OrderedDict([('type', 'unsigned char'),
             ('dimension', 3),
             ('space', 'left-posterior-superior'),
             ('sizes', array([512, 512, 234])),
             ('space directions',
              array([[0.46875, 0.     , 0.     ],
                     [0.     , 0.46875, 0.     ],
                     [0.     , 0.     , 1.5    ]])),
             ('kinds', ['domain', 'domain', 'domain']),
             ('encoding', 'gzip'),
             ('space origin', array([-102.765625, -288.765625,  863.      ])),
             ('Segment0_Color', '0.666667 0 0'),
             ('Segment0_ColorAutoGenerated', '0'),
             ('Segment0_Extent', '327 341 271 285 99 112'),
             ('Segment0_ID', 'Segment_1'),
             ('Segment0_LabelValue', '1'),
             ('Segment0_Layer', '0'),
             ('Segment0_Name', 'L calc 1'),
             ('Segment0_NameAutoGenerated', '0'),
             ('Segment0_Tags',
              'Segmentation.Status:inprogress|TerminologyEntry:S

In [32]:
header = nrrd.read_header('10.img.nrrd')

In [33]:
print(header)

OrderedDict([('type', 'short'), ('dimension', 3), ('space', 'left-posterior-superior'), ('sizes', array([512, 512, 234])), ('space directions', array([[0.46875, 0.     , 0.     ],
       [0.     , 0.46875, 0.     ],
       [0.     , 0.     , 1.5    ]])), ('kinds', ['domain', 'domain', 'domain']), ('endian', 'little'), ('encoding', 'gzip'), ('space origin', array([-102.765625, -288.765625,  863.      ]))])


In [34]:
header_l = nrrd.read_header('10.a.seg.nrrd')

In [35]:
print(header_l)

OrderedDict([('type', 'unsigned char'), ('dimension', 3), ('space', 'left-posterior-superior'), ('sizes', array([512, 512, 234])), ('space directions', array([[0.46875, 0.     , 0.     ],
       [0.     , 0.46875, 0.     ],
       [0.     , 0.     , 1.5    ]])), ('kinds', ['domain', 'domain', 'domain']), ('encoding', 'gzip'), ('space origin', array([-102.765625, -288.765625,  863.      ])), ('Segment0_Color', '0.666667 0 0'), ('Segment0_ColorAutoGenerated', '0'), ('Segment0_Extent', '327 341 271 285 99 112'), ('Segment0_ID', 'Segment_1'), ('Segment0_LabelValue', '1'), ('Segment0_Layer', '0'), ('Segment0_Name', 'L calc 1'), ('Segment0_NameAutoGenerated', '0'), ('Segment0_Tags', 'Segmentation.Status:inprogress|TerminologyEntry:Segmentation category and type - 3D Slicer General Anatomy list~SCT^85756007^Tissue~SCT^85756007^Tissue~^^~Anatomic codes - DICOM master list~^^~^^|'), ('Segment1_Color', '1 0.666667 0'), ('Segment1_ColorAutoGenerated', '0'), ('Segment1_Extent', '327 341 271 285 99

In [11]:
np.set_printoptions(threshold = sys.maxsize)

None


In [19]:
img_data = nrrd.read('10.img.nrrd', index_order='C')

In [20]:
img_data = np.array(img_data)

/var/folders/w2/kjqd2k2x70z1qwx2jy2y7j580000gn/T/ipykernel_2384/3868205268.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  img_data = np.array(img_data)


data.shape

In [21]:
print(img_data.shape)

(2,)


In [22]:
labl_data = nrrd.read('10.a.seg.nrrd', index_order='C')

In [23]:
labl_data = np.array(labl_data)

/var/folders/w2/kjqd2k2x70z1qwx2jy2y7j580000gn/T/ipykernel_2384/619140618.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  labl_data = np.array(labl_data)


In [24]:
print(labl_data.shape)

(2,)


In [55]:
import slicerio
import nrrd
import json

In [52]:
segmentation_info = slicerio.read_segmentation_info("10.a.seg.nrrd")

In [53]:
print(segmentation_info)

{'segments': [{'index': 0, 'color': [0.666667, 0.0, 0.0], 'colorAutoGenerated': False, 'extent': [327, 341, 271, 285, 99, 112], 'id': 'Segment_1', 'labelValue': 1, 'layer': 0, 'name': 'L calc 1', 'nameAutoGenerated': False, 'status': 'inprogress', 'terminology': {'contextName': 'Segmentation category and type - 3D Slicer General Anatomy list', 'category': ['SCT', '85756007', 'Tissue'], 'type': ['SCT', '85756007', 'Tissue']}, 'tags': {}}, {'index': 1, 'color': [1.0, 0.666667, 0.0], 'colorAutoGenerated': False, 'extent': [327, 341, 271, 285, 99, 112], 'id': 'Segment_2', 'labelValue': 2, 'layer': 0, 'name': 'L calc 2', 'nameAutoGenerated': False, 'status': 'inprogress', 'terminology': {'contextName': 'Segmentation category and type - 3D Slicer General Anatomy list', 'category': ['SCT', '85756007', 'Tissue'], 'type': ['SCT', '85756007', 'Tissue']}, 'tags': {}}]}


In [60]:
number_of_segments = len(segmentation_info["segments"])
print(f"Number of segments: {number_of_segments}")

segment_names = slicerio.segment_names(segmentation_info)
print(f"Segment names: {', '.join(segment_names)}")

segment0 = slicerio.segment_from_name(segmentation_info, segment_names[0])
print("First segment info:\n" + json.dumps(segment0, sort_keys=False, indent=4))

segment1 = slicerio.segment_from_name(segmentation_info, segment_names[1])
print("Second segment info:\n" + json.dumps(segment1, sort_keys=False, indent=4))

Number of segments: 2
Segment names: L calc 1, L calc 2
First segment info:
{
    "index": 0,
    "color": [
        0.666667,
        0.0,
        0.0
    ],
    "colorAutoGenerated": false,
    "extent": [
        327,
        341,
        271,
        285,
        99,
        112
    ],
    "id": "Segment_1",
    "labelValue": 1,
    "layer": 0,
    "name": "L calc 1",
    "nameAutoGenerated": false,
    "status": "inprogress",
    "terminology": {
        "contextName": "Segmentation category and type - 3D Slicer General Anatomy list",
        "category": [
            "SCT",
            "85756007",
            "Tissue"
        ],
        "type": [
            "SCT",
            "85756007",
            "Tissue"
        ]
    },
    "tags": {}
}
Second segment info:
{
    "index": 1,
    "color": [
        1.0,
        0.666667,
        0.0
    ],
    "colorAutoGenerated": false,
    "extent": [
        327,
        341,
        271,
        285,
        99,
        112
    ],
    "

In [64]:
input_filename = "10.a.seg.nrrd"
#output_filename = "path/to/SegmentationExtracted.seg.nrrd"
segment_names_to_labels = [(segment_names[0], 1), (segment_names[1], 2)]
# Read voxels and metadata from a .seg.nrrd file
voxels, header = nrrd.read(input_filename)
# Get selected segments in a 3D numpy array and updated segment metadata
extracted_voxels, extracted_header = slicerio.extract_segments(voxels, header, segmentation_info, segment_names_to_labels)

In [65]:
print(extracted_voxels)

[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]


In [66]:
print(extracted_header)

{'type': 'unsigned char', 'dimension': 3, 'space': 'left-posterior-superior', 'sizes': array([512, 512, 234]), 'space directions': array([[0.46875, 0.     , 0.     ],
       [0.     , 0.46875, 0.     ],
       [0.     , 0.     , 1.5    ]]), 'kinds': ['domain', 'domain', 'domain'], 'encoding': 'gzip', 'space origin': array([-102.765625, -288.765625,  863.      ]), 'Segmentation_ContainedRepresentationNames': 'Binary labelmap|', 'Segmentation_ConversionParameters': 'Decimation factor|0.0|Desired reduction in the total number of polygons. Range: 0.0 (no decimation) to 1.0 (as much simplification as possible). Value of 0.8 typically reduces data set size by 80% without losing too much details.&Smoothing factor|0.5|Smoothing factor. Range: 0.0 (no smoothing) to 1.0 (strong smoothing).&Compute surface normals|1|Compute surface normals. 1 (default) = surface normals are computed. 0 = surface normals are not computed (slightly faster but produces less smooth surface display).&Joint smoothing|0

In [70]:
segmentation_info = slicerio.read_segmentation_info("94.a.seg.nrrd")
print(segmentation_info)

{'segments': [{'index': 0, 'color': [0.666667, 0.0, 0.0], 'colorAutoGenerated': False, 'extent': [294, 305, 254, 257, 71, 76], 'id': 'Segment_1', 'labelValue': 1, 'layer': 0, 'name': 'L calc 1', 'nameAutoGenerated': False, 'status': 'inprogress', 'terminology': {'contextName': 'Segmentation category and type - 3D Slicer General Anatomy list', 'category': ['SCT', '85756007', 'Tissue'], 'type': ['SCT', '85756007', 'Tissue']}, 'tags': {}}]}


In [71]:
number_of_segments = len(segmentation_info["segments"])
print(f"Number of segments: {number_of_segments}")

segment_names = slicerio.segment_names(segmentation_info)
print(f"Segment names: {', '.join(segment_names)}")

segment0 = slicerio.segment_from_name(segmentation_info, segment_names[0])
print("First segment info:\n" + json.dumps(segment0, sort_keys=False, indent=4))

Number of segments: 1
Segment names: L calc 1
First segment info:
{
    "index": 0,
    "color": [
        0.666667,
        0.0,
        0.0
    ],
    "colorAutoGenerated": false,
    "extent": [
        294,
        305,
        254,
        257,
        71,
        76
    ],
    "id": "Segment_1",
    "labelValue": 1,
    "layer": 0,
    "name": "L calc 1",
    "nameAutoGenerated": false,
    "status": "inprogress",
    "terminology": {
        "contextName": "Segmentation category and type - 3D Slicer General Anatomy list",
        "category": [
            "SCT",
            "85756007",
            "Tissue"
        ],
        "type": [
            "SCT",
            "85756007",
            "Tissue"
        ]
    },
    "tags": {}
}


In [78]:
segmentationNode = slicer.util.getNode("Segmentation")
sourceSegmentName = "Segment_1"

segmentation = segmentationNode.GetSegmentation()
sourceSegmentId = segmentation.GetSegmentIdBySegmentName(sourceSegmentName)
segmentation.CopySegmentFromSegmentation(segmentation, sourceSegmentId)

NameError: name 'getNode' is not defined

In [ ]:
segmentationNode = getNode("Segmentation")

# Compute segment statistics
import SegmentStatistics
segStatLogic = SegmentStatistics.SegmentStatisticsLogic()
segStatLogic.getParameterNode().SetParameter("Segmentation", segmentationNode.GetID())
segStatLogic.computeStatistics()
stats = segStatLogic.getStatistics()

# Display volume of each segment
for segmentId in stats["SegmentIDs"]:
    volume_cm3 = stats[segmentId,"LabelmapSegmentStatisticsPlugin.volume_cm3"]
    segmentName = segmentationNode.GetSegmentation().GetSegment(segmentId).GetName()
    print(f"{segmentName} volume = {volume_cm3} cm3")