In [1]:
%pylab inline
import os
import nrrd

Populating the interactive namespace from numpy and matplotlib


In [2]:
DATAPATH = '/raid/mpsych/CACTAS/DATA/ESUS/'

In [15]:
image =[]
label =[]

In [9]:
for i in range()
    a = np.empty((i, 512, 512))

In [23]:
for f in os.listdir(DATAPATH):
    if f.endswith('img.nrrd'):
        current_id = f.split('.')[0]
        im, h = nrrd.read(DATAPATH + f'{current_id}.img.nrrd')
        #print(im)
        for z in range(im.shape[2]):
            a[z] = np.array((im...., 512, 512))
        #image.append(a)
        #print(image)
        #np.save(DATAPATH + image.npy, image, allow_pickle=True)

[[[-1005  -996  -994 ... -1003 -1000  -997]
  [-1005  -999  -995 ... -1001 -1000  -998]
  [-1003 -1002 -1001 ... -1000  -999  -997]
  ...
  [  167   179   180 ...  -994  -996  -995]
  [  171   174   156 ...  -991  -994  -993]
  [  153   156   120 ...  -990  -993  -990]]

 [[-1005  -995  -998 ... -1004 -1002 -1000]
  [-1008  -997  -996 ... -1002 -1002 -1002]
  [-1006  -999  -998 ... -1002 -1002 -1002]
  ...
  [  165   200   197 ...  -994  -993  -994]
  [  186   204   181 ...  -994  -991  -992]
  [  179   179   153 ...  -995  -992  -990]]

 [[-1001  -999 -1003 ... -1004 -1002 -1002]
  [-1003  -999 -1001 ... -1003 -1002 -1004]
  [-1004  -999 -1000 ... -1004 -1003 -1005]
  ...
  [  138   200   202 ...  -994  -990  -995]
  [  171   220   199 ...  -997  -989  -993]
  [  185   205   182 ...  -998  -991  -993]]

 ...

 [[ -999  -999  -998 ...  -991  -991  -988]
  [-1000  -996  -997 ...  -990  -989  -988]
  [-1001  -993  -995 ...  -987  -988  -989]
  ...
  [ -833  -810  -812 ... -1005 -1003 -10

KeyboardInterrupt: 