In [1]:
%pylab inline
import os
import json

Populating the interactive namespace from numpy and matplotlib


In [2]:
DATAPATH = '/raid/mpsych/CACTAS/DATA/ESUS/'

In [3]:
images_file = os.path.join(DATAPATH, 'image.npy')
labels_file = os.path.join(DATAPATH, 'label.npy')
images = np.load(images_file)
labels = np.load(labels_file)

In [4]:
with open("images_data.json", "r") as fp:
    image_data = json.load(fp)

In [5]:
with open("labels_data.json", "r") as fp:
    label_data = json.load(fp)

In [6]:
len(images), len(labels)

(14893, 14893)

In [7]:
len(image_data), len(label_data)

(64, 64)

In [8]:
#for values in image_data.values():
#   print(values)

In [9]:
images = images.astype(np.float64)
labels = labels.astype(np.float64)

In [ ]:
# 1: apply normalization for the whole file

In [10]:
images = (images - images.min()) / (images.max() - images.min())    

In [11]:
images.min(), images.max()

(0.0, 1.0)

In [12]:
#images

array([[[0.02627807, 0.02627807, 0.02675585, ..., 0.30625896,
         0.30721452, 0.30291448],
        [0.02627807, 0.0255614 , 0.02603918, ..., 0.30578118,
         0.3107979 , 0.30912566],
        [0.02723364, 0.02675585, 0.02651696, ..., 0.2993311 ,
         0.30721452, 0.31055901],
        ...,
        [0.02771142, 0.02747253, 0.02723364, ..., 0.06736742,
         0.07142857, 0.07118968],
        [0.02723364, 0.02723364, 0.02699474, ..., 0.06832298,
         0.07095079, 0.07118968],
        [0.02795031, 0.02795031, 0.02795031, ..., 0.06617296,
         0.06760631, 0.06951744]],

       [[0.02842809, 0.02771142, 0.02699474, ..., 0.30912566,
         0.3079312 , 0.30363115],
        [0.02866699, 0.0281892 , 0.02771142, ..., 0.31414238,
         0.31509795, 0.30912566],
        [0.02771142, 0.02771142, 0.02771142, ..., 0.31414238,
         0.31892021, 0.31533684],
        ...,
        [0.02771142, 0.02842809, 0.02914477, ..., 0.07286192,
         0.07429527, 0.07286192],
        [0.0

In [ ]:
# split using patient id to the start of the slices in the array

In [13]:
for i, j in enumerate(image_data):
    if i == round(len(image_data) * 0.8):
        X_train = images[0:image_data[j]]
        X_val = images[image_data[j]:]
        #print(i, j, image_data[j])
        #print(X_train)
        #print(X_val)

[[[0.02627807 0.02627807 0.02675585 ... 0.30625896 0.30721452 0.30291448]
  [0.02627807 0.0255614  0.02603918 ... 0.30578118 0.3107979  0.30912566]
  [0.02723364 0.02675585 0.02651696 ... 0.2993311  0.30721452 0.31055901]
  ...
  [0.02771142 0.02747253 0.02723364 ... 0.06736742 0.07142857 0.07118968]
  [0.02723364 0.02723364 0.02699474 ... 0.06832298 0.07095079 0.07118968]
  [0.02795031 0.02795031 0.02795031 ... 0.06617296 0.06760631 0.06951744]]

 [[0.02842809 0.02771142 0.02699474 ... 0.30912566 0.3079312  0.30363115]
  [0.02866699 0.0281892  0.02771142 ... 0.31414238 0.31509795 0.30912566]
  [0.02771142 0.02771142 0.02771142 ... 0.31414238 0.31892021 0.31533684]
  ...
  [0.02771142 0.02842809 0.02914477 ... 0.07286192 0.07429527 0.07286192]
  [0.02771142 0.02842809 0.02866699 ... 0.06951744 0.06975633 0.06999522]
  [0.0281892  0.02842809 0.0281892  ... 0.06473961 0.06402293 0.06617296]]

 [[0.02890588 0.02866699 0.02723364 ... 0.30936455 0.30363115 0.29503106]
  [0.02795031 0.028428

In [14]:
for i, j in enumerate(label_data):
    if i == round(len(label_data) * 0.8):
        y_train = images[0:label_data[j]]
        y_val = images[label_data[j]:]
        #print(i, j, label_data[j])
        #print(X_train)
        #print(X_val)

[[[0.02627807 0.02627807 0.02675585 ... 0.30625896 0.30721452 0.30291448]
  [0.02627807 0.0255614  0.02603918 ... 0.30578118 0.3107979  0.30912566]
  [0.02723364 0.02675585 0.02651696 ... 0.2993311  0.30721452 0.31055901]
  ...
  [0.02771142 0.02747253 0.02723364 ... 0.06736742 0.07142857 0.07118968]
  [0.02723364 0.02723364 0.02699474 ... 0.06832298 0.07095079 0.07118968]
  [0.02795031 0.02795031 0.02795031 ... 0.06617296 0.06760631 0.06951744]]

 [[0.02842809 0.02771142 0.02699474 ... 0.30912566 0.3079312  0.30363115]
  [0.02866699 0.0281892  0.02771142 ... 0.31414238 0.31509795 0.30912566]
  [0.02771142 0.02771142 0.02771142 ... 0.31414238 0.31892021 0.31533684]
  ...
  [0.02771142 0.02842809 0.02914477 ... 0.07286192 0.07429527 0.07286192]
  [0.02771142 0.02842809 0.02866699 ... 0.06951744 0.06975633 0.06999522]
  [0.0281892  0.02842809 0.0281892  ... 0.06473961 0.06402293 0.06617296]]

 [[0.02890588 0.02866699 0.02723364 ... 0.30936455 0.30363115 0.29503106]
  [0.02795031 0.028428