In [8]:
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
import random
import pandas as pd
from skimage.transform import resize
import nrrd
import os
import glob
import mahotas as mh

In [4]:
DATAPATH = '/raid/mpsych/CACTAS/DATA/'
ESUSPATH = '/raid/mpsych/CACTAS/DATA/ESUS/'
IMGPATH = '/raid/mpsych/CACTAS/DATA/ESUS_NPY/IMG'
LBPATH = '/raid/mpsych/CACTAS/DATA/ESUS_NPY/LABEL'

In [ ]:
# Convert nrrd to npy and save file

In [3]:
for f in os.listdir(ESUSPATH):
    if f.endswith('img.nrrd'):
        current_id = f.split('.')[0]
        im, h = nrrd.read(ESUSPATH + f'{current_id}.img.nrrd')
        imarray = np.array(im)
        
        #if f'{current_id}.npy' not in DATAPATH + 'ESUS_NPY/IMG':
        #    np.save(DATAPATH + 'ESUS_NPY/IMG' + f'/{current_id}.npy', imarray)
    if f.endswith('seg.nrrd'):
        current_id = f.split('.')[0]
        im, h = nrrd.read(ESUSPATH + f'{current_id}.img.nrrd')
        imarray = np.array(im)

        #if f'{current_id}.npy' not in DATAPATH + 'ESUS_NPY/LABEL':
        #    np.save(DATAPATH + 'ESUS_NPY/LABEL' + f'/{current_id}.npy', imarray)

In [27]:
for i in range(5):
    for f in os.listdir(IMGPATH):
        current_id = f.split('.')[0]
        img = np.load(IMGPATH + f'/{current_id}.npy', allow_pickle=True)

        print(img.shape)
        print(img)

(512, 512, 230)
[[[-1013 -1006 -1006 ... -1001  -999  -999]
  [-1015 -1010 -1007 ... -1001 -1000 -1001]
  [-1011 -1010 -1010 ... -1002 -1001 -1003]
  ...
  [ -917  -919  -915 ... -1005 -1004  -999]
  [ -919  -920  -916 ... -1005 -1004 -1005]
  [ -922  -923  -922 ... -1005 -1006 -1007]]

 [[-1009 -1003 -1005 ... -1000  -999  -999]
  [-1010 -1006 -1006 ... -1000 -1002 -1002]
  [-1010 -1008 -1009 ... -1002 -1002 -1003]
  ...
  [ -919  -915  -911 ... -1006 -1003  -995]
  [ -921  -920  -915 ... -1006 -1003 -1000]
  [ -922  -925  -923 ... -1008 -1005 -1004]]

 [[-1008 -1008 -1002 ...  -998 -1000 -1000]
  [-1006 -1005 -1002 ...  -999 -1001 -1004]
  [-1006 -1007 -1004 ... -1001 -1000 -1002]
  ...
  [ -920  -919  -911 ... -1005 -1002  -994]
  [ -921  -923  -916 ... -1005 -1002  -996]
  [ -926  -926  -922 ... -1006 -1004 -1000]]

 ...

 [[ -989  -983  -991 ...  -999  -996  -998]
  [ -984  -980  -987 ... -1000  -997  -996]
  [ -985  -981  -988 ...  -998  -997  -996]
  ...
  [ -915  -923  -910 ...

(512, 512, 245)
[[[ -989  -989  -997 ... -1005 -1000  -996]
  [ -985  -980  -991 ... -1005  -999  -996]
  [ -983  -970  -989 ... -1005  -998  -994]
  ...
  [ -339  -326  -339 ... -1009 -1013 -1013]
  [ -395  -363  -343 ... -1008 -1013 -1014]
  [ -390  -354  -356 ... -1007 -1016 -1017]]

 [[-1001  -992  -989 ... -1011 -1006 -1000]
  [ -991  -988  -992 ... -1011 -1007 -1001]
  [ -984  -978  -993 ... -1010 -1006 -1001]
  ...
  [ -309  -303  -315 ... -1010 -1013 -1012]
  [ -379  -360  -349 ... -1010 -1014 -1016]
  [ -397  -368  -380 ... -1010 -1015 -1017]]

 [[ -998  -994  -991 ... -1013 -1008  -999]
  [ -995  -995  -994 ... -1014 -1010 -1001]
  [ -988  -988  -993 ... -1013 -1010 -1003]
  ...
  [ -276  -282  -295 ... -1010 -1015 -1014]
  [ -349  -345  -370 ... -1012 -1015 -1016]
  [ -388  -370  -409 ... -1011 -1013 -1016]]

 ...

 [[-1003 -1000  -994 ... -1012 -1016 -1007]
  [ -997 -1006  -991 ... -1010 -1015 -1006]
  [ -977 -1006  -994 ... -1009 -1013 -1006]
  ...
  [   74    70    74 ...

(512, 512, 222)
[[[-1010 -1008  -998 ... -1006 -1006 -1007]
  [-1010 -1012  -996 ... -1009 -1007 -1007]
  [-1008 -1014  -995 ... -1011 -1005 -1005]
  ...
  [ -789  -787  -802 ... -1002  -998 -1002]
  [ -613  -589  -582 ... -1001  -997 -1003]
  [ -361  -344  -343 ...  -996  -995  -998]]

 [[ -999 -1015 -1008 ... -1004 -1003 -1003]
  [-1009 -1016 -1006 ... -1008 -1006 -1006]
  [-1011 -1016 -1005 ... -1010 -1003 -1005]
  ...
  [ -806  -807  -816 ... -1003 -1001 -1002]
  [ -681  -663  -661 ...  -999  -999 -1001]
  [ -458  -451  -445 ...  -995  -996  -996]]

 [[ -991 -1013 -1013 ...  -996  -995  -992]
  [-1002 -1014 -1010 ...  -997  -997  -995]
  [-1011 -1015 -1005 ...  -998  -997  -995]
  ...
  [ -797  -815  -809 ... -1001 -1001 -1003]
  [ -736  -734  -731 ...  -996 -1001 -1000]
  [ -570  -568  -562 ...  -994  -999  -997]]

 ...

 [[-1001 -1004 -1000 ...  -996  -994  -996]
  [-1001 -1004  -994 ...  -994  -993  -996]
  [-1000 -1006  -998 ...  -995  -996 -1000]
  ...
  [ -906  -898  -920 ...

(512, 512, 237)
[[[-1002 -1003  -993 ...  -993  -994 -1002]
  [-1000 -1003  -991 ...  -996  -996 -1002]
  [-1003 -1003  -993 ...  -998 -1000 -1003]
  ...
  [ -982  -981  -984 ... -1004  -999 -1004]
  [ -977  -985  -985 ... -1004  -999 -1003]
  [ -985  -988  -988 ... -1004 -1000 -1003]]

 [[-1000 -1001  -995 ...  -993  -996 -1004]
  [ -999 -1002  -994 ...  -996  -998 -1004]
  [-1000 -1001  -995 ...  -996 -1001 -1005]
  ...
  [ -981  -984  -982 ... -1005 -1000 -1006]
  [ -977  -986  -986 ... -1006 -1000 -1006]
  [ -981  -987  -987 ... -1005 -1000 -1005]]

 [[ -999  -998 -1000 ...  -993  -997 -1005]
  [ -997  -997 -1000 ...  -994  -998 -1006]
  [ -997  -996  -998 ...  -995 -1001 -1004]
  ...
  [ -983  -985  -982 ... -1004 -1003 -1005]
  [ -979  -984  -983 ... -1008 -1002 -1006]
  [ -978  -982  -980 ... -1006 -1001 -1004]]

 ...

 [[-1002 -1004 -1008 ...  -992  -994  -996]
  [-1001 -1002 -1005 ...  -992  -994  -996]
  [ -998  -999 -1001 ...  -993  -995  -996]
  ...
  [ -977  -975  -979 ...

(512, 512, 254)
[[[-1002 -1002 -1009 ... -1003 -1009 -1010]
  [ -999 -1008 -1014 ... -1000 -1005 -1009]
  [ -998 -1011 -1009 ... -1001 -1003 -1007]
  ...
  [ -951  -941  -932 ...  -998 -1004 -1003]
  [ -955  -936  -919 ...  -997 -1003 -1003]
  [ -947  -934  -921 ...  -996 -1001 -1001]]

 [[-1002  -999 -1006 ... -1000 -1000 -1006]
  [-1002 -1000 -1013 ... -1002 -1002 -1005]
  [ -999 -1009 -1014 ... -1005 -1003 -1003]
  ...
  [ -954  -938  -935 ...  -996 -1000 -1005]
  [ -947  -925  -922 ...  -995 -1001 -1003]
  [ -930  -920  -922 ...  -997 -1001 -1001]]

 [[-1000  -997 -1003 ...  -995  -992  -997]
  [-1007  -996 -1005 ...  -996  -996  -995]
  [-1009 -1005 -1012 ...  -995  -998  -992]
  ...
  [ -958  -944  -938 ...  -995 -1000 -1005]
  [ -950  -928  -931 ...  -995  -999 -1001]
  [ -933  -916  -926 ...  -998 -1000  -999]]

 ...

 [[ -997 -1007 -1007 ...  -994  -994  -996]
  [-1006 -1002 -1014 ...  -994  -996  -998]
  [-1013 -1002 -1011 ...  -994  -996  -995]
  ...
  [ -879  -879  -890 ...

(512, 512, 176)
[[[-1015 -1005 -1000 ...  -988  -998 -1007]
  [-1005 -1001 -1001 ...  -998  -998 -1001]
  [ -989  -995 -1002 ... -1005  -999  -992]
  ...
  [ -889  -899  -920 ... -1002 -1006  -992]
  [ -897  -898  -909 ... -1013 -1019 -1004]
  [ -896  -895  -893 ... -1018 -1022 -1013]]

 [[-1011  -994 -1006 ... -1006 -1006 -1011]
  [-1005  -992 -1004 ... -1006 -1006 -1011]
  [ -994  -994 -1003 ... -1010 -1009 -1003]
  ...
  [ -908  -910  -924 ... -1014 -1020 -1003]
  [ -908  -908  -905 ... -1019 -1021 -1015]
  [ -903  -900  -895 ... -1018 -1017 -1012]]

 [[-1001  -995 -1000 ... -1012 -1003 -1007]
  [ -989  -996  -997 ... -1010 -1004 -1007]
  [ -975  -998  -997 ... -1013 -1010 -1003]
  ...
  [ -922  -912  -927 ... -1016 -1018 -1012]
  [ -919  -916  -907 ... -1019 -1010 -1012]
  [ -912  -905  -899 ... -1007  -978  -993]]

 ...

 [[ -998  -978  -966 ... -1004 -1011 -1011]
  [ -993  -964  -962 ... -1000 -1005 -1010]
  [ -967  -942  -954 ... -1003 -1003 -1006]
  ...
  [ -939  -931  -927 ...

(512, 512, 176)
[[[-1015 -1005 -1000 ...  -988  -998 -1007]
  [-1005 -1001 -1001 ...  -998  -998 -1001]
  [ -989  -995 -1002 ... -1005  -999  -992]
  ...
  [ -889  -899  -920 ... -1002 -1006  -992]
  [ -897  -898  -909 ... -1013 -1019 -1004]
  [ -896  -895  -893 ... -1018 -1022 -1013]]

 [[-1011  -994 -1006 ... -1006 -1006 -1011]
  [-1005  -992 -1004 ... -1006 -1006 -1011]
  [ -994  -994 -1003 ... -1010 -1009 -1003]
  ...
  [ -908  -910  -924 ... -1014 -1020 -1003]
  [ -908  -908  -905 ... -1019 -1021 -1015]
  [ -903  -900  -895 ... -1018 -1017 -1012]]

 [[-1001  -995 -1000 ... -1012 -1003 -1007]
  [ -989  -996  -997 ... -1010 -1004 -1007]
  [ -975  -998  -997 ... -1013 -1010 -1003]
  ...
  [ -922  -912  -927 ... -1016 -1018 -1012]
  [ -919  -916  -907 ... -1019 -1010 -1012]
  [ -912  -905  -899 ... -1007  -978  -993]]

 ...

 [[ -998  -978  -966 ... -1004 -1011 -1011]
  [ -993  -964  -962 ... -1000 -1005 -1010]
  [ -967  -942  -954 ... -1003 -1003 -1006]
  ...
  [ -939  -931  -927 ...

(512, 512, 209)
[[[ -984  -989  -981 ...  -996 -1001  -999]
  [ -984  -983  -980 ... -1000 -1001  -999]
  [ -985  -977  -979 ... -1003  -999 -1003]
  ...
  [ -865  -874  -879 ...  -998  -996  -996]
  [ -874  -880  -884 ...  -997  -993  -996]
  [ -879  -870  -883 ...  -996  -995  -996]]

 [[ -982  -983  -981 ...  -999 -1002 -1001]
  [ -985  -983  -973 ...  -998 -1001 -1001]
  [ -988  -980  -975 ... -1001  -999 -1004]
  ...
  [ -869  -876  -877 ... -1000  -996  -992]
  [ -875  -879  -879 ...  -999  -996  -993]
  [ -880  -874  -875 ...  -995  -998  -995]]

 [[ -982  -980  -983 ... -1002 -1001 -1000]
  [ -985  -985  -977 ...  -999 -1000 -1003]
  [ -990  -987  -976 ... -1000 -1001 -1004]
  ...
  [ -876  -878  -881 ... -1002  -999  -992]
  [ -877  -875  -878 ... -1002 -1001  -994]
  [ -882  -872  -871 ...  -998  -999  -994]]

 ...

 [[ -983  -990  -981 ...  -998  -990 -1000]
  [ -987  -987  -974 ...  -998  -993  -998]
  [ -985  -987  -983 ...  -996  -996 -1000]
  ...
  [ -890  -912  -907 ...

(512, 512, 236)
[[[-1009  -985  -986 ...  -992  -990  -992]
  [ -999  -985  -980 ...  -992  -991  -992]
  [ -971  -982  -981 ...  -992  -995  -994]
  ...
  [ -911  -902  -889 ... -1003  -998 -1004]
  [ -925  -924  -920 ... -1000  -993  -999]
  [ -928  -930  -940 ...  -991  -990  -992]]

 [[-1000  -982  -989 ...  -997  -997  -999]
  [-1001  -984  -975 ...  -998  -997  -997]
  [ -983  -986  -972 ...  -995  -999  -997]
  ...
  [ -920  -913  -891 ... -1005 -1001 -1002]
  [ -924  -937  -931 ... -1001  -999  -995]
  [ -924  -933  -942 ...  -995  -995  -991]]

 [[ -983  -989 -1009 ... -1010 -1005 -1005]
  [ -997  -992 -1001 ... -1012 -1007 -1004]
  [ -994  -993  -989 ... -1009 -1007 -1004]
  ...
  [ -925  -931  -911 ... -1007 -1004  -999]
  [ -925  -947  -938 ... -1002 -1005  -994]
  [ -925  -935  -932 ...  -999 -1004  -992]]

 ...

 [[-1012  -996  -974 ...  -998 -1000  -995]
  [-1004 -1009  -987 ...  -997  -993  -997]
  [ -990 -1015 -1018 ...  -992  -990  -997]
  ...
  [ -888  -899  -881 ...

(512, 512, 226)
[[[-1011  -998  -995 ... -1002  -999 -1000]
  [-1012  -998 -1001 ... -1007 -1000 -1002]
  [-1005 -1001 -1002 ... -1010 -1005 -1005]
  ...
  [ -282  -288  -283 ... -1012 -1006  -999]
  [  -94   -99   -90 ... -1012 -1007  -998]
  [  -17   -18   -34 ... -1006 -1006  -997]]

 [[-1006  -983  -998 ...  -997  -994  -998]
  [-1007  -988 -1005 ... -1000  -996  -998]
  [-1000  -991 -1005 ... -1003 -1002 -1001]
  ...
  [ -372  -375  -376 ... -1007 -1005 -1001]
  [ -133  -133  -132 ... -1005 -1006 -1000]
  [  -31   -26   -40 ... -1001 -1004  -997]]

 [[ -997  -985 -1002 ...  -997  -995 -1000]
  [-1000  -987 -1005 ...  -997  -996  -997]
  [ -995  -988 -1004 ...  -996  -998  -996]
  ...
  [ -480  -470  -467 ...  -999 -1001 -1002]
  [ -221  -203  -205 ...  -995 -1001 -1004]
  [  -83   -54   -75 ...  -993 -1000 -1001]]

 ...

 [[ -992  -991  -980 ... -1006 -1006 -1002]
  [ -979  -991  -985 ... -1006 -1007 -1002]
  [ -971  -991  -997 ... -1003 -1006 -1002]
  ...
  [ -971  -973  -976 ...

(512, 512, 293)
[[[-1024 -1024 -1024 ... -1024 -1024 -1024]
  [-1024 -1024 -1024 ... -1024 -1024 -1024]
  [-1024 -1024 -1024 ... -1024 -1024 -1024]
  ...
  [-1024 -1024 -1024 ... -1024 -1024 -1024]
  [-1024 -1024 -1024 ... -1024 -1024 -1024]
  [-1024 -1024 -1024 ... -1024 -1024 -1024]]

 [[-1024 -1024 -1024 ... -1024 -1024 -1024]
  [-1024 -1024 -1024 ... -1024 -1024 -1024]
  [-1024 -1024 -1024 ... -1024 -1024 -1024]
  ...
  [-1024 -1024 -1024 ... -1024 -1024 -1024]
  [-1024 -1024 -1024 ... -1024 -1024 -1024]
  [-1024 -1024 -1024 ... -1024 -1024 -1024]]

 [[-1024 -1024 -1024 ... -1024 -1024 -1024]
  [-1024 -1024 -1024 ... -1024 -1024 -1024]
  [-1024 -1024 -1024 ... -1024 -1024 -1024]
  ...
  [-1024 -1024 -1024 ... -1024 -1024 -1024]
  [-1024 -1024 -1024 ... -1024 -1024 -1024]
  [-1024 -1024 -1024 ... -1024 -1024 -1024]]

 ...

 [[-1024 -1024 -1024 ... -1024 -1024 -1024]
  [-1024 -1024 -1024 ... -1024 -1024 -1024]
  [-1024 -1024 -1024 ... -1024 -1024 -1024]
  ...
  [-1024 -1024 -1024 ...

(512, 512, 279)
[[[ -992  -998 -1006 ... -1000  -999  -996]
  [ -990  -995 -1005 ...  -999  -998  -994]
  [ -994  -998 -1010 ...  -995  -997 -1002]
  ...
  [ -902  -903  -897 ... -1009 -1001 -1001]
  [ -901  -899  -909 ... -1004 -1001 -1001]
  [ -900  -900  -905 ...  -999 -1002 -1001]]

 [[ -990  -994 -1008 ... -1001  -999  -994]
  [ -986  -992 -1005 ...  -999  -999 -1000]
  [ -987  -993 -1005 ...  -996 -1000 -1010]
  ...
  [ -900  -896  -898 ... -1009 -1005 -1001]
  [ -897  -895  -915 ... -1008 -1002 -1000]
  [ -899  -899  -906 ... -1002 -1001 -1000]]

 [[ -994  -997 -1003 ...  -999  -997 -1000]
  [ -990  -998 -1001 ...  -997  -998 -1006]
  [ -988  -997  -997 ...  -994  -997 -1006]
  ...
  [ -902  -896  -906 ... -1001 -1007 -1005]
  [ -898  -897  -912 ... -1006 -1006 -1002]
  [ -902  -898  -901 ... -1004 -1003  -999]]

 ...

 [[-1010 -1000 -1011 ... -1005 -1001 -1002]
  [-1011 -1006 -1010 ... -1001 -1000 -1002]
  [-1008 -1005 -1002 ...  -998 -1000 -1002]
  ...
  [ -944  -945  -957 ...

(512, 512, 200)
[[[-1001 -1007 -1005 ...  -999 -1004  -994]
  [ -999 -1004 -1001 ... -1000 -1002  -995]
  [ -993  -994  -996 ... -1001  -998 -1000]
  ...
  [ -857  -856  -864 ... -1004 -1004 -1008]
  [ -899  -887  -904 ... -1011 -1013 -1004]
  [ -911  -894  -902 ... -1006 -1009 -1000]]

 [[ -990  -992 -1008 ... -1001 -1003 -1006]
  [ -992 -1000 -1002 ... -1000 -1005 -1003]
  [ -987  -999  -993 ... -1000 -1003 -1002]
  ...
  [ -836  -840  -864 ... -1009 -1009 -1004]
  [ -900  -889  -913 ... -1012 -1009  -998]
  [ -911  -901  -909 ... -1003 -1002  -998]]

 [[ -992  -992 -1000 ... -1004  -997 -1008]
  [ -995  -999  -999 ... -1004 -1000 -1006]
  [ -994 -1005  -996 ... -1003 -1001 -1004]
  ...
  [ -805  -821  -845 ... -1011 -1009  -999]
  [ -886  -888  -902 ... -1009 -1003  -994]
  [ -901  -903  -903 ... -1000  -998  -997]]

 ...

 [[-1010 -1014  -994 ... -1004 -1007  -997]
  [-1015 -1012  -998 ... -1003 -1006 -1001]
  [ -993  -989 -1004 ... -1002 -1003 -1001]
  ...
  [ -147  -167  -159 ...

(512, 512, 217)
[[[ -993  -990  -996 ...  -992  -997 -1004]
  [-1002  -992 -1004 ...  -993  -998 -1005]
  [-1009  -995 -1008 ...  -995  -998 -1007]
  ...
  [ -954  -953  -958 ... -1001 -1013 -1001]
  [ -961  -965  -964 ... -1000 -1009 -1000]
  [ -958  -969  -964 ... -1000 -1007 -1001]]

 [[ -994  -993  -997 ...  -992  -994 -1003]
  [-1005  -994 -1003 ...  -992  -995 -1004]
  [-1012  -997 -1007 ...  -993  -996 -1006]
  ...
  [ -953  -955  -968 ... -1001 -1012 -1002]
  [ -962  -969  -972 ...  -998 -1010 -1001]
  [ -964  -972  -965 ...  -998 -1007 -1001]]

 [[ -989 -1003 -1002 ...  -999  -999 -1007]
  [-1000  -999 -1002 ...  -997 -1000 -1008]
  [-1009  -998 -1004 ...  -995 -1000 -1009]
  ...
  [ -954  -961  -975 ...  -999 -1009 -1004]
  [ -961  -971  -978 ...  -996 -1009 -1004]
  [ -959  -968  -969 ...  -997 -1008 -1001]]

 ...

 [[-1015 -1009 -1010 ...  -995  -996  -995]
  [-1013 -1001  -997 ...  -995  -996  -997]
  [-1009  -998  -988 ...  -997  -998  -999]
  ...
  [ -947  -944  -948 ...

(512, 512, 241)
[[[ -991 -1009 -1018 ... -1001 -1000 -1005]
  [ -998 -1004 -1017 ... -1001  -998 -1004]
  [-1003 -1001 -1016 ... -1000  -999 -1004]
  ...
  [ -916  -928  -922 ... -1002  -998 -1003]
  [ -913  -931  -924 ... -1002  -996 -1007]
  [ -914  -928  -924 ...  -998  -998 -1008]]

 [[ -996 -1014 -1017 ... -1004 -1002 -1005]
  [-1004 -1010 -1017 ... -1005 -1001 -1006]
  [-1011 -1003 -1012 ... -1004 -1004 -1008]
  ...
  [ -922  -939  -922 ...  -999  -997 -1000]
  [ -919  -935  -918 ... -1001  -997 -1002]
  [ -922  -929  -921 ... -1001  -998 -1004]]

 [[-1008 -1012 -1010 ... -1006 -1002 -1006]
  [-1009 -1009 -1013 ... -1004 -1003 -1007]
  [-1009 -1001 -1009 ... -1002 -1006 -1009]
  ...
  [ -931  -938  -919 ...  -997  -998  -999]
  [ -922  -930  -918 ... -1000  -998 -1001]
  [ -919  -922  -924 ...  -999  -998 -1001]]

 ...

 [[-1008 -1003 -1008 ... -1003 -1003  -996]
  [-1001  -993 -1003 ... -1004 -1005 -1000]
  [-1002  -995 -1000 ... -1005 -1006 -1001]
  ...
  [ -888  -890  -891 ...

(512, 512, 245)
[[[-1006 -1011 -1013 ... -1017 -1014 -1020]
  [-1006 -1012 -1016 ... -1016 -1015 -1020]
  [-1005 -1011 -1017 ... -1018 -1016 -1020]
  ...
  [  -91  -128   -98 ...  -995  -992  -997]
  [ -109  -124   -94 ...  -994  -993  -996]
  [ -120  -105   -86 ...  -997  -996  -996]]

 [[-1004 -1008 -1006 ... -1015 -1009 -1012]
  [-1004 -1009 -1010 ... -1013 -1010 -1012]
  [-1004 -1012 -1015 ... -1012 -1012 -1014]
  ...
  [  -86  -124   -98 ...  -995  -994  -997]
  [ -103  -119   -96 ...  -995  -997  -998]
  [ -110   -98   -90 ...  -998  -999  -998]]

 [[-1003 -1007  -998 ... -1011 -1006 -1007]
  [-1005 -1007 -1000 ... -1009 -1006 -1007]
  [-1005 -1008 -1003 ... -1008 -1007 -1008]
  ...
  [  -91  -113   -90 ...  -998  -998 -1000]
  [  -99  -107   -94 ... -1000 -1002 -1001]
  [  -99   -91   -97 ... -1002 -1004 -1000]]

 ...

 [[-1000  -997  -995 ... -1004 -1007 -1006]
  [-1001  -998  -988 ... -1002 -1007 -1007]
  [-1001 -1002  -987 ... -1000 -1005 -1006]
  ...
  [  -88   -98  -119 ...

(512, 512, 201)
[[[-1005  -996  -994 ... -1003 -1000  -997]
  [-1005  -999  -995 ... -1001 -1000  -998]
  [-1003 -1002 -1001 ... -1000  -999  -997]
  ...
  [  167   179   180 ...  -994  -996  -995]
  [  171   174   156 ...  -991  -994  -993]
  [  153   156   120 ...  -990  -993  -990]]

 [[-1005  -995  -998 ... -1004 -1002 -1000]
  [-1008  -997  -996 ... -1002 -1002 -1002]
  [-1006  -999  -998 ... -1002 -1002 -1002]
  ...
  [  165   200   197 ...  -994  -993  -994]
  [  186   204   181 ...  -994  -991  -992]
  [  179   179   153 ...  -995  -992  -990]]

 [[-1001  -999 -1003 ... -1004 -1002 -1002]
  [-1003  -999 -1001 ... -1003 -1002 -1004]
  [-1004  -999 -1000 ... -1004 -1003 -1005]
  ...
  [  138   200   202 ...  -994  -990  -995]
  [  171   220   199 ...  -997  -989  -993]
  [  185   205   182 ...  -998  -991  -993]]

 ...

 [[ -999  -999  -998 ...  -991  -991  -988]
  [-1000  -996  -997 ...  -990  -989  -988]
  [-1001  -993  -995 ...  -987  -988  -989]
  ...
  [ -833  -810  -812 ...

(512, 512, 239)
[[[ -925  -884  -849 ...  -984  -993  -993]
  [ -951  -938  -909 ...  -984  -993  -993]
  [ -974  -973  -963 ...  -986  -995  -996]
  ...
  [ -945  -904  -934 ...  -996  -996  -995]
  [ -937  -918  -919 ...  -996  -997  -998]
  [ -939  -944  -907 ...  -995  -996  -997]]

 [[ -929  -875  -837 ...  -990  -998 -1001]
  [ -959  -930  -898 ...  -987  -997 -1000]
  [ -978  -973  -964 ...  -987  -996  -998]
  ...
  [ -952  -914  -942 ...  -997  -996  -996]
  [ -951  -946  -931 ...  -997  -996  -998]
  [ -946  -967  -926 ...  -996  -995  -997]]

 [[ -946  -879  -840 ... -1003 -1011 -1011]
  [ -972  -930  -896 ... -1001 -1011 -1009]
  [ -981  -973  -967 ...  -999 -1007 -1008]
  ...
  [ -948  -944  -950 ...  -997  -995  -995]
  [ -953  -965  -946 ...  -998  -995  -995]
  [ -943  -963  -944 ...  -997  -994  -994]]

 ...

 [[  -75  -107  -110 ...  -999 -1002  -996]
  [ -106  -102  -127 ... -1002 -1004  -995]
  [ -132   -92  -127 ... -1001 -1003  -995]
  ...
  [ -919  -911  -910 ...

(512, 512, 194)
[[[ -999 -1001  -998 ... -1002 -1007 -1005]
  [ -997 -1002  -996 ... -1000 -1009 -1006]
  [ -998 -1003  -997 ... -1002 -1011 -1009]
  ...
  [   25   -26  -111 ... -1014 -1010 -1015]
  [  -41  -145  -247 ... -1011 -1011 -1015]
  [ -176  -348  -466 ... -1008 -1013 -1013]]

 [[ -996  -996  -995 ... -1002 -1010 -1008]
  [ -995  -997  -995 ... -1003 -1013 -1008]
  [ -996  -997  -994 ... -1005 -1014 -1009]
  ...
  [   88    66    35 ... -1012 -1012 -1015]
  [   74    -7   -63 ... -1008 -1012 -1014]
  [  -18  -162  -260 ... -1007 -1014 -1013]]

 [[ -996  -994  -991 ... -1003 -1011 -1008]
  [ -998  -996  -993 ... -1004 -1012 -1008]
  [ -997  -997  -994 ... -1005 -1011 -1006]
  ...
  [   83    84    84 ... -1010 -1014 -1015]
  [   94    50    35 ... -1007 -1015 -1015]
  [   42   -47  -110 ... -1008 -1016 -1014]]

 ...

 [[ -998 -1004 -1005 ... -1004 -1002 -1003]
  [ -995 -1005 -1006 ... -1004 -1004 -1004]
  [ -989 -1003 -1008 ... -1004 -1006 -1005]
  ...
  [  -41   -67   -79 ...

(512, 512, 525)
[[[ -972  -968  -966 ...  -985  -989  -983]
  [-1010  -994  -983 ...  -990  -990  -983]
  [-1023 -1012  -997 ...  -996  -984  -986]
  ...
  [ -286  -269  -259 ... -1008 -1013 -1001]
  [  -66  -107  -106 ... -1012  -997  -994]
  [   20   -45   -60 ... -1007  -994  -990]]

 [[ -965  -980  -989 ...  -988  -998  -996]
  [ -975  -988  -999 ...  -991  -995  -994]
  [-1001 -1005 -1008 ...  -993  -989  -989]
  ...
  [ -350  -357  -372 ...  -998 -1010  -992]
  [ -114  -165  -196 ... -1002  -995  -995]
  [  -13   -29   -52 ...  -998  -993  -993]]

 [[ -997 -1006 -1009 ... -1003 -1007 -1013]
  [ -975  -995 -1006 ... -1005 -1007 -1014]
  [ -984 -1003 -1012 ... -1004 -1006 -1009]
  ...
  [ -453  -448  -482 ...  -996 -1007  -995]
  [ -220  -239  -291 ...  -994  -995  -999]
  [  -76   -48   -78 ...  -988  -994 -1000]]

 ...

 [[-1005 -1019 -1020 ...  -993  -988 -1000]
  [-1024 -1024 -1019 ... -1000  -996  -999]
  [-1024 -1024 -1017 ... -1003 -1007 -1001]
  ...
  [ -862  -904  -882 ...

(512, 512, 255)
[[[-1002 -1003 -1009 ... -1003  -999  -996]
  [ -995 -1002 -1015 ... -1003  -999  -995]
  [ -999  -992 -1003 ... -1002  -997  -997]
  ...
  [ -903  -896  -902 ...  -997 -1000  -998]
  [ -876  -863  -881 ...  -995 -1003 -1002]
  [ -766  -765  -764 ...  -995 -1005 -1003]]

 [[ -998 -1007 -1000 ... -1008 -1000  -995]
  [ -986 -1005 -1017 ... -1006 -1001  -997]
  [ -987 -1001 -1017 ... -1004  -999  -999]
  ...
  [ -906  -895  -916 ... -1003 -1001 -1003]
  [ -904  -884  -891 ... -1002  -999 -1000]
  [ -838  -825  -815 ... -1001 -1001  -997]]

 [[-1012 -1012  -986 ... -1004  -997  -994]
  [ -995 -1011 -1013 ... -1003  -997  -996]
  [ -983 -1002 -1020 ... -1002  -995  -996]
  ...
  [ -915  -899  -914 ... -1004 -1003 -1004]
  [ -915  -905  -896 ... -1004 -1001 -1001]
  [ -873  -869  -856 ... -1001 -1000  -996]]

 ...

 [[-1005 -1017  -994 ...  -997  -999  -996]
  [-1000 -1013 -1000 ...  -997  -996  -992]
  [ -995 -1004  -995 ...  -999  -994  -989]
  ...
  [ -882  -913  -915 ...

(512, 512, 242)
[[[ -996  -993  -998 ...  -998  -999  -997]
  [ -997  -994  -973 ... -1000  -998  -995]
  [ -985  -988  -973 ...  -998  -999  -995]
  ...
  [ -964  -951  -932 ...  -989  -989  -995]
  [ -934  -952  -935 ...  -987  -993  -997]
  [ -921  -920  -939 ...  -994  -999 -1003]]

 [[-1000  -996 -1016 ...  -998 -1001  -997]
  [-1009  -996  -987 ... -1001 -1001  -997]
  [-1008  -992  -960 ...  -999 -1001  -999]
  ...
  [ -967  -947  -941 ...  -988  -990  -994]
  [ -936  -949  -940 ...  -992  -994  -994]
  [ -940  -925  -933 ...  -999  -999  -998]]

 [[-1001 -1002 -1021 ... -1001 -1002 -1002]
  [-1006 -1000 -1019 ... -1004 -1001 -1003]
  [-1016  -999  -986 ... -1001  -999 -1004]
  ...
  [ -953  -964  -948 ...  -991  -994  -996]
  [ -931  -957  -936 ... -1000  -995  -994]
  [ -945  -928  -927 ... -1003  -997  -994]]

 ...

 [[-1011 -1010  -983 ...  -995  -993  -991]
  [ -993  -993  -976 ...  -991  -993  -993]
  [ -973  -973  -981 ...  -988  -991  -992]
  ...
  [ -933  -916  -931 ...

(512, 512, 250)
[[[ -994  -992  -993 ...  -995  -996  -997]
  [ -996  -992  -991 ...  -997  -997  -997]
  [ -996  -992  -995 ...  -999  -998  -997]
  ...
  [ -795  -800  -803 ...  -994  -994 -1000]
  [ -652  -659  -642 ...  -996  -996 -1000]
  [ -395  -399  -379 ...  -997  -998  -997]]

 [[ -991  -980  -990 ...  -996 -1001  -998]
  [ -996  -989  -991 ...  -997 -1001  -998]
  [ -997  -989  -989 ...  -998 -1001  -998]
  ...
  [ -843  -838  -840 ...  -992  -995  -999]
  [ -737  -732  -717 ...  -993  -994  -999]
  [ -515  -508  -493 ...  -997  -994  -996]]

 [[ -988  -974  -988 ... -1001 -1007  -998]
  [ -990  -977  -990 ... -1000 -1005  -998]
  [ -990  -982  -989 ...  -999 -1000  -995]
  ...
  [ -882  -875  -860 ...  -992  -998  -999]
  [ -796  -789  -773 ...  -992  -993  -998]
  [ -618  -605  -590 ...  -995  -991  -995]]

 ...

 [[ -997  -997  -989 ...  -996  -997  -997]
  [-1001  -994  -996 ...  -997  -997 -1001]
  [ -999  -994 -1002 ...  -996  -996 -1003]
  ...
  [ -947  -939  -941 ...

(512, 512, 169)
[[[-1016 -1000 -1004 ... -1011 -1005 -1001]
  [-1013 -1000 -1004 ... -1012 -1006 -1001]
  [-1010 -1002 -1004 ... -1008 -1007 -1002]
  ...
  [   78   108   115 ... -1002 -1000  -990]
  [  -61   -55   -40 ... -1004 -1004  -996]
  [ -239  -249  -232 ... -1004 -1005  -995]]

 [[-1014 -1003 -1009 ... -1009 -1001 -1001]
  [-1011  -996 -1004 ... -1010 -1003 -1001]
  [-1008  -996 -1003 ... -1008 -1003 -1001]
  ...
  [   92   123   128 ... -1001 -1000  -990]
  [   21    16    23 ... -1003 -1002  -997]
  [ -155  -166  -147 ... -1003 -1003  -996]]

 [[-1013 -1003 -1008 ... -1008 -1002 -1002]
  [-1011 -1001 -1005 ... -1010 -1000 -1002]
  [-1010  -997 -1003 ... -1009 -1001 -1003]
  ...
  [   90   128   117 ... -1001 -1000  -988]
  [   68    70    72 ... -1001 -1000  -997]
  [  -62   -70   -45 ... -1000  -998  -997]]

 ...

 [[-1008 -1007 -1010 ...  -998 -1001 -1005]
  [-1006 -1003 -1007 ...  -998 -1002 -1003]
  [-1003 -1003 -1007 ...  -998 -1000 -1003]
  ...
  [ -953  -932  -937 ...

(512, 512, 264)
[[[ -999  -988  -986 ... -1005 -1006 -1004]
  [-1006  -997  -982 ... -1007 -1008 -1006]
  [-1007 -1008 -1001 ... -1008 -1009 -1005]
  ...
  [ -884  -913  -934 ...  -998  -999 -1000]
  [ -892  -907  -930 ...  -997  -998 -1004]
  [ -922  -912  -919 ...  -996  -997 -1003]]

 [[ -999  -994 -1001 ... -1000 -1000  -996]
  [-1002  -992  -992 ... -1002 -1003  -997]
  [-1007  -992  -992 ... -1002 -1004  -998]
  ...
  [ -895  -916  -935 ...  -999 -1000  -999]
  [ -903  -908  -929 ...  -997  -997 -1001]
  [ -926  -911  -919 ...  -994  -996 -1002]]

 [[ -991 -1001 -1010 ... -1000 -1001  -995]
  [ -994  -992  -997 ... -1000 -1003  -997]
  [ -998  -983  -980 ...  -998 -1003  -998]
  ...
  [ -912  -928  -941 ... -1000 -1002 -1000]
  [ -923  -916  -935 ...  -998 -1000 -1000]
  [ -931  -915  -924 ...  -995  -998 -1000]]

 ...

 [[ -980  -991 -1002 ... -1002 -1008 -1003]
  [ -969  -994 -1000 ... -1000 -1005 -1002]
  [ -976  -997 -1007 ...  -998 -1003 -1000]
  ...
  [ -890  -866  -858 ...

(512, 512, 239)
[[[ -965  -980  -982 ...  -995 -1006 -1005]
  [ -977  -979  -990 ...  -996 -1005 -1006]
  [ -984  -975  -992 ... -1000 -1005 -1007]
  ...
  [ -796  -825  -840 ... -1002 -1004 -1006]
  [ -807  -827  -847 ... -1002 -1007 -1006]
  [ -836  -834  -839 ...  -999 -1006 -1004]]

 [[ -953  -972  -980 ...  -997 -1008 -1013]
  [ -957  -980  -988 ...  -996 -1006 -1011]
  [ -972  -982  -992 ...  -998 -1007 -1008]
  ...
  [ -779  -828  -841 ... -1004 -1006 -1010]
  [ -795  -831  -847 ... -1005 -1009 -1003]
  [ -835  -834  -838 ... -1004 -1004  -996]]

 [[ -969  -977  -980 ... -1000 -1008 -1014]
  [ -962  -985  -981 ...  -996 -1007 -1011]
  [ -969  -991  -988 ...  -995 -1008 -1007]
  ...
  [ -784  -819  -840 ... -1004 -1004 -1010]
  [ -787  -826  -844 ... -1002 -1005  -999]
  [ -824  -830  -834 ... -1000  -997  -992]]

 ...

 [[ -980  -988  -986 ... -1002 -1000 -1001]
  [ -991  -995  -999 ... -1001 -1002 -1003]
  [ -989  -982  -998 ... -1001 -1002 -1004]
  ...
  [ -866  -844  -865 ...

(512, 512, 237)
[[[ -988  -987 -1004 ... -1008  -998 -1003]
  [ -994 -1004 -1000 ...  -998  -994 -1002]
  [ -997 -1007  -992 ...  -994  -995  -999]
  ...
  [ -915  -915  -921 ...  -999 -1001 -1005]
  [ -918  -914  -920 ... -1000  -999 -1005]
  [ -915  -918  -916 ... -1000  -998 -1004]]

 [[ -984  -982 -1001 ... -1002  -996 -1002]
  [ -985  -988 -1001 ...  -995  -995  -999]
  [ -995  -999  -991 ...  -998  -999  -996]
  ...
  [ -916  -915  -926 ...  -999 -1004 -1003]
  [ -917  -918  -923 ...  -999 -1002 -1005]
  [ -917  -921  -921 ...  -999  -998 -1003]]

 [[ -985  -982  -988 ...  -999 -1000 -1004]
  [ -981  -979  -994 ...  -999 -1003 -1001]
  [ -983  -984  -988 ... -1001 -1004 -1000]
  ...
  [ -916  -912  -927 ... -1002 -1002  -999]
  [ -916  -916  -922 ... -1001 -1005 -1005]
  [ -919  -921  -925 ... -1000 -1002 -1005]]

 ...

 [[ -988  -993 -1003 ...  -998  -999 -1001]
  [ -990  -996 -1010 ...  -996  -999 -1005]
  [ -997  -995 -1004 ...  -997 -1001 -1008]
  ...
  [ -912  -920  -923 ...

(512, 512, 245)
[[[   75    73    59 ...  -997  -998  -998]
  [   68    69    65 ...  -996  -998  -997]
  [   52    53    66 ...  -995  -997  -997]
  ...
  [ -932  -967  -932 ...  -939  -941  -935]
  [ -965  -979  -960 ...  -940  -942  -937]
  [ -971  -968  -964 ...  -943  -944  -941]]

 [[   69    64    71 ...  -997  -998  -997]
  [   64    65    69 ...  -996  -998  -997]
  [   48    57    57 ...  -995  -997  -998]
  ...
  [ -911  -962  -935 ...  -941  -943  -939]
  [ -949  -972  -960 ...  -939  -942  -938]
  [ -957  -959  -959 ...  -938  -941  -938]]

 [[   56    51    70 ...  -998  -998  -996]
  [   49    57    61 ...  -995  -998  -998]
  [   41    59    48 ...  -994  -997  -999]
  ...
  [ -902  -956  -950 ...  -943  -944  -942]
  [ -937  -966  -968 ...  -941  -944  -940]
  [ -942  -953  -959 ...  -938  -942  -937]]

 ...

 [[ -859  -928  -975 ...  -995  -994  -998]
  [ -863  -905  -967 ...  -995  -996  -997]
  [ -870  -876  -950 ...  -994  -996  -997]
  ...
  [ -207  -192  -181 ...

(512, 512, 264)
[[[ -981  -993 -1005 ...  -997  -993  -997]
  [ -988 -1000 -1013 ... -1001  -993  -998]
  [-1001 -1008 -1015 ... -1000  -996  -997]
  ...
  [ -507  -507  -570 ...  -999 -1009 -1016]
  [ -248  -250  -276 ...  -997 -1008 -1017]
  [  -13   -17    -6 ...  -996 -1006 -1016]]

 [[ -984  -987 -1004 ...  -997  -996  -997]
  [ -979  -987 -1007 ... -1002  -996 -1000]
  [ -987 -1005 -1012 ... -1007 -1003 -1008]
  ...
  [ -604  -612  -645 ...  -998 -1009 -1017]
  [ -380  -369  -364 ...  -996 -1008 -1017]
  [ -127  -114  -102 ...  -996 -1006 -1015]]

 [[-1002  -996 -1004 ...  -993  -993  -996]
  [ -988  -986  -998 ...  -994  -994  -998]
  [ -984  -998 -1002 ... -1001 -1002 -1007]
  ...
  [ -685  -703  -706 ...  -995 -1009 -1019]
  [ -494  -478  -460 ...  -996 -1011 -1019]
  [ -228  -210  -202 ...  -999 -1009 -1015]]

 ...

 [[ -961  -973  -985 ...  -998 -1005 -1016]
  [ -984  -977  -994 ... -1001 -1006 -1018]
  [-1005  -996  -994 ... -1002 -1010 -1017]
  ...
  [ -850  -850  -871 ...

(512, 512, 230)
[[[-1010 -1002  -994 ...  -998  -998 -1000]
  [-1010  -997  -993 ...  -997  -998  -999]
  [-1014 -1000  -998 ... -1001  -998  -998]
  ...
  [ -780  -799  -776 ...  -997 -1002 -1002]
  [ -574  -599  -578 ...  -998 -1002 -1004]
  [ -251  -272  -270 ... -1002 -1001 -1004]]

 [[-1014 -1002 -1000 ...  -997  -999 -1001]
  [-1010  -995  -997 ...  -998  -997 -1000]
  [-1007  -997 -1000 ... -1002  -998 -1000]
  ...
  [ -833  -838  -813 ... -1000 -1003 -1004]
  [ -683  -699  -677 ...  -999 -1002 -1006]
  [ -396  -413  -404 ... -1002 -1003 -1005]]

 [[-1014 -1007 -1007 ...  -998 -1000 -1000]
  [-1008  -999 -1003 ... -1000 -1000  -999]
  [ -999  -995 -1000 ... -1002 -1000 -1000]
  ...
  [ -860  -849  -837 ... -1001 -1001 -1005]
  [ -768  -766  -758 ...  -999 -1000 -1005]
  [ -531  -531  -529 ... -1001 -1000 -1003]]

 ...

 [[ -999 -1000 -1004 ...  -995  -998 -1003]
  [-1000  -998 -1004 ...  -996 -1000 -1000]
  [ -997  -994 -1000 ...  -999 -1000  -997]
  ...
  [ -981  -985  -983 ...

(512, 512, 261)
[[[-1012 -1009 -1003 ...  -998 -1003 -1005]
  [-1014 -1011  -985 ... -1001 -1007 -1002]
  [-1009 -1000  -974 ... -1000 -1005 -1000]
  ...
  [-1023 -1023 -1024 ... -1024 -1024 -1024]
  [-1024 -1024 -1024 ... -1024 -1024 -1024]
  [-1024 -1024 -1024 ... -1024 -1024 -1024]]

 [[ -996  -997 -1009 ...  -999 -1002 -1003]
  [-1009 -1014 -1006 ... -1003 -1004 -1002]
  [-1007 -1010  -984 ...  -999 -1000 -1001]
  ...
  [-1023 -1023 -1024 ... -1024 -1024 -1024]
  [-1024 -1024 -1024 ... -1024 -1024 -1024]
  [-1024 -1024 -1024 ... -1024 -1024 -1024]]

 [[ -981  -973  -993 ...  -999  -999 -1000]
  [ -988  -997 -1007 ... -1000 -1000 -1002]
  [ -988 -1005  -995 ...  -996  -996 -1002]
  ...
  [-1024 -1023 -1024 ... -1024 -1024 -1024]
  [-1024 -1024 -1024 ... -1024 -1024 -1024]
  [-1024 -1024 -1024 ... -1024 -1024 -1024]]

 ...

 [[-1001 -1011 -1009 ... -1001  -996  -993]
  [ -992 -1008 -1010 ... -1005  -998  -990]
  [ -977  -994  -998 ... -1005 -1000  -991]
  ...
  [-1022 -1023 -1023 ...

(512, 512, 240)
[[[ -997 -1004 -1001 ...  -999  -996  -996]
  [ -997 -1001 -1000 ...  -998  -999  -997]
  [ -998 -1000 -1001 ...  -998 -1001 -1001]
  ...
  [ -849  -840  -868 ... -1001 -1007 -1006]
  [ -866  -869  -897 ... -1003 -1005 -1005]
  [ -888  -897  -907 ... -1004 -1003 -1005]]

 [[-1000 -1002 -1002 ... -1000  -999  -998]
  [-1000 -1001 -1002 ...  -999 -1000 -1002]
  [-1001 -1001 -1001 ...  -998  -999 -1005]
  ...
  [ -855  -835  -855 ... -1000 -1005 -1004]
  [ -871  -862  -886 ... -1003 -1005 -1004]
  [ -889  -892  -903 ... -1005 -1004 -1004]]

 [[-1000  -999  -999 ... -1000 -1001 -1005]
  [-1003 -1002 -1002 ...  -999 -1000 -1008]
  [-1004 -1004 -1001 ...  -998  -998 -1008]
  ...
  [ -860  -838  -857 ...  -998 -1002 -1001]
  [ -879  -863  -884 ... -1002 -1004 -1002]
  [ -894  -889  -900 ... -1005 -1003 -1003]]

 ...

 [[-1008  -998  -995 ...  -995  -997 -1003]
  [-1008 -1003  -996 ...  -996  -997 -1002]
  [-1008 -1004  -997 ...  -995  -998 -1003]
  ...
  [-1024 -1024 -1020 ...

(512, 512, 218)
[[[ -999  -993  -994 ... -1002  -999  -994]
  [ -997  -994  -997 ... -1008 -1000  -994]
  [ -995  -995  -998 ... -1008 -1001  -996]
  ...
  [ -925  -914  -920 ...  -999 -1003 -1001]
  [ -926  -928  -918 ... -1002 -1006 -1003]
  [ -928  -940  -926 ... -1002 -1003 -1005]]

 [[ -998  -992  -990 ... -1006 -1001  -994]
  [ -998  -994  -992 ... -1008 -1001  -996]
  [ -996  -994  -995 ... -1004 -1003 -1000]
  ...
  [ -927  -917  -918 ...  -996  -998 -1001]
  [ -925  -932  -917 ...  -999 -1002 -1004]
  [ -927  -942  -924 ... -1002 -1002 -1006]]

 [[ -996  -997  -991 ... -1006 -1000  -997]
  [ -999  -998  -993 ... -1003 -1000 -1000]
  [ -999  -997  -994 ...  -999 -1002 -1005]
  ...
  [ -923  -916  -915 ...  -998  -997 -1003]
  [ -919  -929  -915 ...  -999  -998 -1003]
  [ -921  -938  -920 ... -1000  -999 -1005]]

 ...

 [[ -997  -995  -998 ...  -996  -995  -995]
  [ -999  -998 -1000 ...  -997  -993  -995]
  [-1001 -1000 -1000 ...  -996  -994  -993]
  ...
  [ -892  -910  -900 ...

(512, 512, 258)
[[[ -996 -1013 -1015 ...  -997  -997  -999]
  [ -987  -999 -1011 ...  -998  -998 -1002]
  [ -994  -990 -1000 ...  -998  -998 -1001]
  ...
  [ -930  -917  -919 ...  -999  -996  -994]
  [ -928  -914  -922 ... -1005 -1002 -1001]
  [ -927  -926  -926 ... -1016 -1010 -1003]]

 [[-1011 -1016 -1012 ...  -999  -994  -996]
  [ -996 -1008 -1012 ...  -994  -996  -999]
  [ -988  -993 -1006 ...  -992  -995  -998]
  ...
  [ -929  -911  -913 ... -1014 -1016 -1007]
  [ -937  -921  -925 ... -1016 -1016 -1011]
  [ -937  -932  -930 ... -1017 -1012 -1002]]

 [[-1016 -1016 -1012 ... -1001  -997  -998]
  [-1013 -1016 -1012 ...  -995  -997  -997]
  [ -996 -1005 -1008 ...  -990  -994  -996]
  ...
  [ -929  -915  -915 ... -1005 -1013 -1011]
  [ -937  -931  -930 ... -1004 -1008 -1014]
  [ -930  -935  -924 ...  -997 -1000  -999]]

 ...

 [[-1002 -1008 -1009 ... -1000  -996  -999]
  [-1002 -1018 -1023 ...  -999  -997  -997]
  [-1000 -1020 -1023 ... -1002 -1000  -995]
  ...
  [ -143  -239  -232 ...

(512, 512, 240)
[[[ -997  -987  -996 ... -1002  -995 -1000]
  [ -997  -999 -1000 ...  -998  -996  -998]
  [ -996 -1001 -1001 ...  -995  -998  -997]
  ...
  [ -609  -657  -673 ... -1002  -999  -998]
  [ -446  -472  -475 ... -1000 -1001  -999]
  [ -250  -254  -248 ...  -999 -1003 -1001]]

 [[-1002  -990  -989 ... -1006 -1003 -1007]
  [-1005 -1003  -998 ... -1003 -1006 -1006]
  [ -999 -1008 -1005 ...  -999 -1006 -1005]
  ...
  [ -664  -696  -722 ... -1000 -1000  -998]
  [ -538  -564  -562 ...  -999  -999  -998]
  [ -330  -347  -339 ... -1001  -999  -997]]

 [[-1010 -1001  -984 ... -1002 -1002 -1003]
  [-1013 -1008  -989 ... -1000 -1005 -1005]
  [ -997 -1012  -998 ...  -998 -1006 -1006]
  ...
  [ -700  -719  -745 ... -1000 -1000  -998]
  [ -624  -645  -640 ... -1000  -999  -997]
  [ -421  -443  -437 ... -1003  -999  -997]]

 ...

 [[ -980  -981 -1002 ...  -996  -996  -997]
  [ -980  -973 -1002 ...  -998  -999  -999]
  [-1002  -996 -1003 ...  -996  -999  -998]
  ...
  [ -940  -947  -913 ...

In [ ]:
# make array list

In [29]:
loadedimages = []

for f in os.listdir(IMGPATH):
    current_id = f.split('.')[0]
    loadedimages.append(np.load(IMGPATH + f'/{current_id}.npy', allow_pickle=True).copy())

#imgs = np.asarray(loadedimages)

In [34]:
loadedimages

[array([[[-1013, -1006, -1006, ..., -1001,  -999,  -999],
         [-1015, -1010, -1007, ..., -1001, -1000, -1001],
         [-1011, -1010, -1010, ..., -1002, -1001, -1003],
         ...,
         [ -917,  -919,  -915, ..., -1005, -1004,  -999],
         [ -919,  -920,  -916, ..., -1005, -1004, -1005],
         [ -922,  -923,  -922, ..., -1005, -1006, -1007]],
 
        [[-1009, -1003, -1005, ..., -1000,  -999,  -999],
         [-1010, -1006, -1006, ..., -1000, -1002, -1002],
         [-1010, -1008, -1009, ..., -1002, -1002, -1003],
         ...,
         [ -919,  -915,  -911, ..., -1006, -1003,  -995],
         [ -921,  -920,  -915, ..., -1006, -1003, -1000],
         [ -922,  -925,  -923, ..., -1008, -1005, -1004]],
 
        [[-1008, -1008, -1002, ...,  -998, -1000, -1000],
         [-1006, -1005, -1002, ...,  -999, -1001, -1004],
         [-1006, -1007, -1004, ..., -1001, -1000, -1002],
         ...,
         [ -920,  -919,  -911, ..., -1005, -1002,  -994],
         [ -921,  -923, 

In [30]:
imgs = np.asarray(loadedimages)

/tmp/ipykernel_3814892/2324286279.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  imgs = np.asarray(loadedimages)


ValueError: could not broadcast input array from shape (512,512,230) into shape (512,512)

In [ ]:
imgs

In [ ]:
loadedmasks = []

for f in os.listdir(LBPATH):
    current_id = f.split('.')[0]
    loadedmasks += [np.load(LBPATH + f'/{current_id}.npy', allow_pickle=True).copy()]
    
masks = np.asarray(loadedmasks)

In [ ]:
masks

In [65]:
DATAPATH = '/raid/mpsych/CACTAS/DATA/ESUS/'

In [66]:
DATASETS = sorted(v for v in os.listdir(DATAPATH))

In [77]:
len_d = len(DATASETS)

In [78]:
len_d // 2

66

In [12]:
images = []
labels = []

image_patches = []
label_patches = []

DATAPATH = '/raid/mpsych/CACTAS/DATA/ESUS/'
DATASETS = sorted(v for v in os.listdir(DATAPATH))
for i,d in enumerate(DATASETS):
    #print(i, d) # 0 - 131
    D = DATASETS[i]

    files = glob.glob(DATAPATH + "*.nrrd")
    label_file = [os.path.join(DATAPATH, D, s) for s in files if 'seg' in s]
    image_file = [os.path.join(DATAPATH, D, i) for i in files if not 'seg' in i]

    label_file = [s for s in label_file if os.path.isfile(s)][i]
    image_file = [i for i in image_file if os.path.isfile(i)][i]

    #print(i)
    #print(image_file)
    #print(label_file)

    label_with_header = nrrd.read(label_file)
    image_with_header = nrrd.read(image_file)

    label = label_with_header[0]
    image = image_with_header[0]
    #print("img, label: ", image, label)

    # normalize grayscale to 0..1
    image_normalized = image.copy().astype(np.float64)
    image_normalized = (image_normalized - image_normalized.min()) / (image_normalized.max() - image_normalized.min())
    #print(image_normalized)

    # remove empty slices
    filtered_image = image_normalized.copy()
    filtered_label = label.copy()

    slices_to_remove = []
    
    #print(filtered_label.shape)
    '''
    (512, 512, 258)
    (512, 512, 255)
    (512, 512, 216)
    (512, 512, 245)
    (512, 512, 237)
    (512, 512, 221)
    (512, 512, 390)
    (512, 512, 268)
    (512, 512, 216)
    (512, 512, 221)
    (512, 512, 240)
    (512, 512, 201)
    (512, 512, 217)
    (512, 512, 237)
    (512, 512, 211)
    (512, 512, 236)
    (512, 512, 245)
    (512, 512, 293)
    (512, 512, 264)
    (512, 512, 176)
    (512, 512, 261)
    (512, 512, 176)
    (512, 512, 179)
    (512, 512, 232)
    '''

    for z in range(filtered_label.shape[2]):
        if filtered_label[:,:,z].max() == 0:
            slices_to_remove.append(z)
    
    #print(slices_to_remove)

    slices_to_remove = sorted(slices_to_remove, reverse=True)
    
    '''
    for z in slices_to_remove:
        filtered_image = np.delete(filtered_image, z, 2)
        filtered_label = np.delete(filtered_label, z, 2)
    '''
    
    for z in slices_to_remove:
        if z < filtered_image.shape[2]:
            filtered_image = np.delete(filtered_image, z, 2)
            filtered_label = np.delete(filtered_label, z, 2)

    #print("img: ", filtered_image)
    #print("lb: ", filtered_label)


    # loop thru each slice
    for z in range(filtered_label.shape[2]):

        image_slice = filtered_image[:,:,z:z+1]
        label_slice = filtered_label[:,:,z:z+1]

        # relabel the segments
        relabel, obj = mh.label(label_slice)

        #print('relabeled')

        # loop thru each segment, binarize and crop
        for i in range(1, relabel.max()+1):

            single_label = np.zeros((relabel.shape), relabel.dtype)
            single_label[relabel == i] = 1

            #image_cropped, single_label_cropped = C.Util.crop(image_slice, single_label, target_size=32)
            #def crop(image, label, increase_xy=10, increase_z=0, target_size=None, just_z=False):
            
            increase_xy=10
            increase_z=0
            target_size=32
            just_z=False
            
            bbox = mh.bbox(single_label) # ignore large portion of label since its all 0
                          # to only include annotated plaque regions

            increase_x = increase_xy
            increase_y = increase_xy

            if target_size:
                widthY = bbox[1]-bbox[0]
                widthX = bbox[3]-bbox[2]

                increase_x = (target_size - widthX) // 2
                increase_y = (target_size - widthY) // 2

                bufferY = 0
                if (bbox[0]-increase_y + bbox[1]+increase_y) != target_size:
                    bufferY = 1

                bufferX = 0
                if (bbox[2]-increase_x + bbox[3]+increase_x) != target_size:
                    bufferX = 1
                
            if just_z:
                increase_xy = 0
                bbox[0] = 0
                bbox[1] = image_slice.shape[0]
                bbox[2] = 0
                bbox[3] = image_slice.shape[1]


                # crop label and image according to bbox but make it a little larger
                label_cropped = single_label[bbox[0]-increase_y:bbox[1]+increase_y+bufferY, 
                                  bbox[2]-increase_x:bbox[3]+increase_x+bufferX,
                                  bbox[4]-increase_z:bbox[5]+increase_z]
                image_cropped = image_slice[bbox[0]-increase_y:bbox[1]+increase_y+bufferY, 
                                  bbox[2]-increase_x:bbox[3]+increase_x+bufferX,
                                  bbox[4]-increase_z:bbox[5]+increase_z]




            image_patches.append(image_cropped)
            label_patches.append(single_label_cropped)


NameError: name 'image_cropped' is not defined