In [1]:
%pylab inline
%load_ext autoreload
%autoreload 2

%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib


In [2]:
import os
import mahotas as mh
import nrrd

In [4]:
selected = []
plaque_count = 0
voxel_count_plaque = 0
voxel_count = 0
casecount = 0

In [3]:
image_file = '10.img.nrrd'
label_file = '10.a.seg.nrrd'

In [4]:
from PIL import Image

filename = "10.img.nrrd"
readdata, header = nrrd.read(filename)
print(readdata.shape) # (512, 512, 504)
for i in range(504):
  if i == 200:
    img = np.array(readdata[:,:,i])
    print(img.shape)
    print(np.amax(img))
    img = (np.maximum(img, 0) / img.max()) * 255.0
    img = Image.fromarray(np.uint8(img), mode = "L")
    img.save(f'testrgb{i}.png')
    break

(512, 512, 234)
(512, 512)
1875


In [5]:
image_data, image_header = nrrd.read(image_file)
label_data, label_header = nrrd.read(label_file)

In [15]:
image_data.size * image_data.itemsize #memory size of numpy array in size

122683392

In [16]:
label_data.size * label_data.itemsize

61341696

In [6]:
image_header

OrderedDict([('type', 'short'),
             ('dimension', 3),
             ('space', 'left-posterior-superior'),
             ('sizes', array([512, 512, 234])),
             ('space directions',
              array([[0.46875, 0.     , 0.     ],
                     [0.     , 0.46875, 0.     ],
                     [0.     , 0.     , 1.5    ]])),
             ('kinds', ['domain', 'domain', 'domain']),
             ('endian', 'little'),
             ('encoding', 'gzip'),
             ('space origin', array([-102.765625, -288.765625,  863.      ]))])

In [8]:
label_header

OrderedDict([('type', 'unsigned char'),
             ('dimension', 3),
             ('space', 'left-posterior-superior'),
             ('sizes', array([512, 512, 234])),
             ('space directions',
              array([[0.46875, 0.     , 0.     ],
                     [0.     , 0.46875, 0.     ],
                     [0.     , 0.     , 1.5    ]])),
             ('kinds', ['domain', 'domain', 'domain']),
             ('encoding', 'gzip'),
             ('space origin', array([-102.765625, -288.765625,  863.      ])),
             ('Segment0_Color', '0.666667 0 0'),
             ('Segment0_ColorAutoGenerated', '0'),
             ('Segment0_Extent', '327 341 271 285 99 112'),
             ('Segment0_ID', 'Segment_1'),
             ('Segment0_LabelValue', '1'),
             ('Segment0_Layer', '0'),
             ('Segment0_Name', 'L calc 1'),
             ('Segment0_NameAutoGenerated', '0'),
             ('Segment0_Tags',
              'Segmentation.Status:inprogress|TerminologyEntry:S

In [6]:
image_data.shape

(512, 512, 234)

In [8]:
relabel, obj = mh.label(label_data)

sizes = np.bincount(relabel.flatten())[1:]

In [8]:
sizes

array([ 56, 346])

In [9]:
min_size = sizes.min()
max_size = sizes.max()

In [ ]:
plaque_count = plaque_count + relabel.max()

In [10]:
min_size

56

In [11]:
max_size

346

In [12]:
relabel, obj = mh.label(label_data)

plaque_count += relabel.max()
voxel_count_plaque += np.count_nonzero(relabel)
voxel_count += image_data.shape[0] * image_data.shape[1] * image_data.shape[2]

casecount += 1

In [22]:
relabel

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [13]:
print("{:f}".format(voxel_count_plaque / voxel_count))

0.000007


In [16]:
voxel_count_plaque / plaque_count

201.0

In [19]:
casecount, plaque_count, voxel_count, voxel_count_plaque

(1, 2, 61341696, 402)

In [10]:
# fileter based on labeled region size
sizes = mh.labeled.labeled_size(relabel)

In [15]:
for i in range(len(sizes)):
    print("Size of region " + str(i) + " : " + str(sizes[i]))

Size of region 0 : 61341294
Size of region 1 : 56
Size of region 2 : 346


In [11]:
sizes

array([61341294,       56,      346], dtype=uint32)

In [13]:
# Remove the regions that are less than 1000
too_small = np.where(sizes < sizes[0])
labeled_only_big = mh.labeled.remove_regions(relabel, too_small)

In [14]:
relabeled, n_left = mh.labeled.relabel(relabel)
print('After filtering and relabeling, there are {} left.'.format(n_left))

After filtering and relabeling, there are 2 left.


In [11]:
bbox = mh.bbox(relabel)

NameError: name 'relabel' is not defined

In [10]:
image = image_data
label = relabel

alpha=0.7
vmin=-600
vmax=1000

masked = np.ma.masked_where(label==0, label)

if image.ndim == 3:

    slices = image.shape[2]

else:

    slices = 1

fig = plt.figure(figsize=(slices,3))

#if title:
#    fig.suptitle(title, fontsize=12, fontweight='bold')

for i in range(slices):

    plt.subplot(1, slices, i+1)

    plt.axis('off')

    if slices > 1:
        plt.imshow(image[:,:,i], cmap='gray', vmin=vmin, vmax=vmax)
        plt.imshow(masked[:,:,i], cmap='jet', interpolation='none', alpha=alpha) 
    else:
        plt.imshow(image, cmap='gray', vmin=vmin, vmax=vmax)
        plt.imshow(masked, cmap='jet', interpolation='none', alpha=alpha) 


"\nfor i in range(slices):\n\n    plt.subplot(1, slices, i+1)\n\n    plt.axis('off')\n\n    if slices > 1:\n        plt.imshow(image[:,:,i], cmap='gray', vmin=vmin, vmax=vmax)\n        plt.imshow(masked[:,:,i], cmap='jet', interpolation='none', alpha=alpha) \n    else:\n        plt.imshow(image, cmap='gray', vmin=vmin, vmax=vmax)\n        plt.imshow(masked, cmap='jet', interpolation='none', alpha=alpha) \n"

<Figure size 23400x300 with 0 Axes>