In [1]:
%pylab inline
%load_ext autoreload
%autoreload 2

%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib


In [2]:
import os
import mahotas as mh
import nrrd

In [3]:
selected = []
plaque_count = 0
voxel_count_plaque = 0
voxel_count = 0
casecount = 0

In [4]:
image_file = '10.img.nrrd'
label_file = '10.a.seg.nrrd'

In [26]:
from PIL import Image

filename = "10.img.nrrd"
readdata, header = nrrd.read(filename)
print(readdata.shape) # (512, 512, 504)
for i in range(504):
  if i == 200:
    img = np.array(readdata[:,:,i])
    print(img.shape)
    print(np.amax(img))
    img = (np.maximum(img, 0) / img.max()) * 255.0
    img = Image.fromarray(np.uint8(img), mode = "L")
    img.save(f'testrgb{i}.png')
    break

(512, 512, 234)
(512, 512)
1875


In [5]:
image_data, image_header = nrrd.read(image_file)
label_data, label_header = nrrd.read(label_file)

In [6]:
image_data.shape

(512, 512, 234)

In [7]:
relabel, obj = mh.label(label_data)

sizes = np.bincount(relabel.flatten())[1:]

In [8]:
sizes

array([ 56, 346])

In [9]:
min_size = sizes.min()
max_size = sizes.max()

In [10]:
min_size

56

In [11]:
max_size

346

In [12]:
relabel, obj = mh.label(label_data)

plaque_count += relabel.max()
voxel_count_plaque += np.count_nonzero(relabel)
voxel_count += image_data.shape[0] * image_data.shape[1] * image_data.shape[2]

casecount += 1

In [22]:
relabel

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [13]:
print("{:f}".format(voxel_count_plaque / voxel_count))

0.000007


In [16]:
voxel_count_plaque / plaque_count

201.0

In [19]:
casecount, plaque_count, voxel_count, voxel_count_plaque

(1, 2, 61341696, 402)

In [10]:
# fileter based on labeled region size
sizes = mh.labeled.labeled_size(relabel)

In [15]:
for i in range(len(sizes)):
    print("Size of region " + str(i) + " : " + str(sizes[i]))

Size of region 0 : 61341294
Size of region 1 : 56
Size of region 2 : 346


In [11]:
sizes

array([61341294,       56,      346], dtype=uint32)

In [13]:
# Remove the regions that are less than 1000
too_small = np.where(sizes < sizes[0])
labeled_only_big = mh.labeled.remove_regions(relabel, too_small)

In [14]:
relabeled, n_left = mh.labeled.relabel(relabel)
print('After filtering and relabeling, there are {} left.'.format(n_left))

After filtering and relabeling, there are 2 left.
